-- V4: Add Users and Authentication
-- User management and authentication tables

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    salt TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('ADMIN', 'DOCTOR', 'RECEPCIONISTA')),
    full_name TEXT NOT NULL,
    active INTEGER DEFAULT 1,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    last_login TEXT,
    failed_attempts INTEGER DEFAULT 0,
    locked_until TEXT
);

-- Index for username lookup
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);

-- Index for active users
CREATE INDEX IF NOT EXISTS idx_users_active ON users(active);

-- Insert default admin user (password: admin123 - should be changed on first login)
-- This is a placeholder hash, actual hash will be generated by the application
INSERT OR IGNORE INTO users (username, password_hash, salt, role, full_name)
VALUES ('admin', 'PLACEHOLDER_HASH', 'PLACEHOLDER_SALT', 'ADMIN', 'Administrador');
